hasker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from .settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('account/', include('account.urls')),
    path('', include('question.urls')),
    path('admin/', admin.site.urls),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

question/urls.py
from django.urls import path, include

from .views import *
from .router import router


urlpatterns = [
    path('', QuestionList.as_view(), name='question_list'),
    path('new/', QuestionList.as_view(sort_by_date=True), name='question_list_new'),
    path('question/<int:id>/', QuestionDetail.as_view(), name='question_detail'),
    path('question/create/', QuestionAddView.as_view(), name='question_create'),
    path('likedis/<int:id>/<str:type>/<str:action>/', ChangeLikeDisView.as_view(), name='like_dis'),
    path('tag/<str:name>/', TagDetail.as_view(), name='tag_detail'),
    path('search/', QuestionList.as_view(), name="search"),
    path('api/v1/', include(router.urls)),
]

question/models.py
from django.db import models, transaction
from django.conf import settings
from django.shortcuts import reverse


class MessageQA(models.Model):

    text = models.TextField(max_length=5000)
    date_create = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL)
    dislike = models.ManyToManyField(settings.AUTH_USER_MODEL)

    class Meta:
        abstract = True

    @property
    def votes(self):
        return self.like.count() - self.dislike.count()

    @transaction.atomic
    def vote(self, user, action):
        if action == 'like':
            self.dislike.remove(user)
            if self.like.filter(pk=user.pk).exists():
                self.like.remove(user)
            else:
                self.like.add(user)
        else:
            self.like.remove(user)
            if self.dislike.filter(pk=user.pk).exists():
                self.dislike.remove(user)
            else:
                self.dislike.add(user)


class Tag(models.Model):
    name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag_detail', kwargs={'name': self.name})


class Questions(MessageQA):
    max_tag = 3
    title = models.CharField(max_length=200)

    tags = models.ManyToManyField(Tag, blank=True, related_name='questions')
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="q_like")
    dislike = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="q_dislike")

    def get_absolute_url(self):
        return reverse('question_detail', kwargs={'id': self.id})


class Answer(MessageQA):
    text = models.TextField(max_length=5000)

    question = models.ForeignKey(Questions, related_name="answers", on_delete=models.CASCADE)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="a_like")
    dislike = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="a_dislike")

question/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, DetailView, CreateView, View
from django.db.models import Q, Count, F
from django.core.paginator import Paginator
from django.core.mail import send_mail

from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated

from .models import Questions, Tag, Answer
from .form import QuestionForm, AnswerForm
from .serializers import (QuestionsListSerializer, AnswerSerializer,
                          QuestionDetailSerializer, AnswerCreteSerializer)
from hasker.hasker.settings import HOST_MAIL


class QuestionMixin:
    paginate_by = 2

    class Meta:
        abstract: True

    def get_related_activities(self, queryset):
        queryset = self.sort_by_like(queryset)
        paginator = Paginator(queryset, self.paginate_by)
        page = self.request.GET.get('page')
        activities = paginator.get_page(page)
        return activities

    def get_context_populate_q(self):
        populate_q = Questions.objects.all()
        return self.sort_by_like(populate_q)

    @staticmethod
    def sort_by_like(queryset):
        return queryset.annotate(likes=Count("like"), dislikes=Count("dislike")
                                 , ).order_by(F("dislikes") - F("likes"), '-date_create')


class QuestionList(ListView, QuestionMixin):
    model = Questions
    template_name = 'question/question_list.html'
    paginate_by = 30
    sort_by_date = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['populate_q'] = self.get_context_populate_q()
        return context

    def get_queryset(self):
        queryset = Questions.objects.all()
        question = self.request.GET.get("q")
        if question and 'tag:' in question:
            name_tag = question.split('tag:')[-1]
            tag = get_object_or_404(Tag, name=name_tag)
            queryset = tag.questions.all()
        elif question:
            queryset = queryset.filter(Q(title__contains=question) | Q(text__contains=question))

        if not self.sort_by_date:
            queryset = self.sort_by_like(queryset)
            return queryset

        return queryset.order_by("date_create")


class TagDetail(DetailView, QuestionMixin):
    model = Tag
    template_name = "question/tag_detail.html"
    pk_url_kwarg = "name"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        queryset = context['object'].questions.all()
        activities = self.get_related_activities(queryset)
        context['object'] = activities.object_list
        context['page_obj'] = activities
        context['populate_q'] = self.get_context_populate_q()
        return context


class QuestionDetail(DetailView, QuestionMixin):
    model = Questions
    template_name = "question/question_detail.html"
    pk_url_kwarg = "id"
    login_url = '/account/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        answers = context['object'].answers.all()
        activities = self.get_related_activities(answers)
        context["page_obj"] = activities
        context['answers'] = activities.object_list
        context['answer_form'] = AnswerForm()
        context['populate_q'] = self.get_context_populate_q()
        return context

    def post(self, request, **kwargs):
        if not request.user.is_authenticated:
            return redirect(self.login_url)

        form = AnswerForm(request.POST)
        if form.is_valid():
            question = Questions.objects.get(id=kwargs['id'])
            Answer.objects.create(
                text=form.cleaned_data['text'],
                author=request.user,
                question=question
            )
            try:
                send_mail(f'Hi {request.user}. User {question.author} answered the question',
                          form.cleaned_data['text'],
                          HOST_MAIL,
                          [question.author.email],)
            except Exception as e:
                pass
        return redirect(request.path)


class QuestionAddView(LoginRequiredMixin, CreateView):
    login_url = '/account/login/'
    form_class = QuestionForm
    template_name = "question/question_create.html"

    def get_success_url(self):
        return self.object.get_absolute_url()

    def post(self, request):
        question_form = self.form_class(request.POST)

        if question_form.is_valid():
            question = question_form.save(commit=False)
            question.author = request.user
            question.save()
            tags = question_form.cleaned_data['tags']
            if tags:
                tags = self.create_tag(tags)
                for tag in tags:
                    question.tags.add(tag)
            return redirect(question.get_absolute_url())
        return render(request, "question/question_list.html", {"form": question_form})

    @staticmethod
    def create_tag(tags):
        for name_tag in tags:
            try:
                tag = Tag.objects.get(name=name_tag)
            except ObjectDoesNotExist:
                tag = Tag.objects.create(name=name_tag)
            yield tag


class ChangeLikeDisView(LoginRequiredMixin, View):
    login_url = '/account/login/'
    http_method_names = ['get', ]

    def get(self, request, **kwargs):
        id_obj = kwargs['id']
        type_obj = kwargs['type']
        action = kwargs['action']
        if type_obj == 'answer':
            obj = Answer.objects.get(id=id_obj)
            path_redirect = obj.question.get_absolute_url()
        else:
            obj = Questions.objects.get(id=id_obj)
            path_redirect = obj.get_absolute_url()
        obj.vote(request.user, action)
        return redirect(path_redirect)


'''############# REST API ################'''


class QAMixin:
    def get_serializer_class(self):
        if self.action in self.serializers_class:
            return self.serializers_class[self.action]
        return self.serializers_class['default']


class QuestionsViewSet(QAMixin, ModelViewSet):
    queryset = Questions.objects.all()
    serializers_class = {
        'default': QuestionsListSerializer,
        'retrieve': QuestionDetailSerializer,
    }
    http_method_names = ['get', 'post', 'head']
    permission_classes = [IsAuthenticated]


class AnswerViewSet(QAMixin, ModelViewSet):
    queryset = Answer.objects.all()
    serializers_class = {
        'default': AnswerSerializer,
        'create': AnswerCreteSerializer,
    }
    http_method_names = ['get', 'post', 'head', ]
    permission_classes = [IsAuthenticated]

question/templates/question/question_create.html
{% extends 'index.html' %}

{% block title %}
    New Question
{% endblock %}

{% block content %}

<form method="post" action="{% url 'question_create' %}">
    {% csrf_token %}
    <div class="card col-9 offset-md-3 mt-4">
        <div class="body">
            <h4 class="card-title mt-4 mb-4">Ask a question</h4>
            {% if object.errors %}
                <div class="alert alert-danger">
                    {{ object.errors }}
                </div>
            {% endif %}

            <div class="d-flex form-group row">
                <label class="col-2 col-form-label text-center">Title</label>
                <div class="col-10">
                    <input type="text" name="title" id="id_title" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label text-center">Text</label>
                <div class="col-10">
                    <textarea name="text" id="id_text" class="form-control" rows="8"></textarea>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-2 col-form-label text-center">Tags</label>
                <div class="col-10">
                    <input type="text" name="tags" id="id_tags" class="form-control">
                </div>
            </div>

            <div class="d-flex justify-content-end mt-2">
                <button type="submit" class="btn btn-primary mb-2">Save</button>
            </div>

        </div>
    </div>
</form>
{% endblock %}

question/templates/question/question_detail.html
{% extends 'index.html' %}

{% block title %}
    {{ object.title }}
{% endblock %}

{% block content %}
<div class="list-group">
     <div class="list-group-item d-flex flex-row">
         <div class="col-1 flex-column mt-4">
             <div class="d-flex p-2 justify-content-center">Votes</div>
             <div class="d-flex p-2 justify-content-center">{{ object.votes }}</div>
         </div>
         <div class="col-11 flex-row">
             <div class="d-flex p-2 justify-content-between">
                 <h4>{{ object.text }}</h4>
             </div>
             <div class="d-flex p-2 justify-content-between">
                 <small>Date create: {{ object.date_create }}</small>
                 <small>
                     <img src="{{ object.author.get_avatar}}" width="25" height="25" class="mr-3">
                     {{ object.author }}
                 </small>
            </div>
             <div class="d-flex p-2 justify-content-between">
                 <div class="d-flex p-2">
                     <small>
                        {% for tag in object.tags.all %}
                        <a href="{{ tag.get_absolute_url }}" class="btn btn-success btn-sm btn-tag ml-1">
                            {{ tag.name }}
                        </a>
                        {% endfor %}
                    </small>
                </div>
                {% if user.is_authenticated %}
                 <div class="d-flex p-2">
                     <a href="{% url 'like_dis' id=object.id type='questions' action='like' %}" role="button"
                        class="btn btn-outline-success btn-sm">
                         Like {{ object.like.count }} {{ user.questions.like.count}}
                     </a>
                     <a href="{% url 'like_dis' id=object.id type='questions' action='dislike' %}"  role="button"
                        class="btn btn-danger btn-outline-danger btn-sm ml-2">
                         Dislike {{ object.dislike.count }}
                     </a>
                </div>
                 {% endif %}
             </div>
         </div>
     </div>

    {% for answer in answers.all %}
        {% include 'question/includes/answer_template.html' %}
    {% endfor %}

    {% include 'question/includes/paginator.html' with page_obj=page_obj %}
    {% if user.is_authenticated %}
    <form action="{{ object.get_absolute_url }}" method="post">
        {% csrf_token %}
        <div class="list-group-item d-flex flex-column">
            <h4>Ask a question</h4>
            {{ answer_form.text }}
            <div class="d-flex justify-content-end mt-2">
                <button type="submit" class="btn btn-primary col-3 text-white">Answer</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>
{% endblock %}

{% block populate %}
{% if user.is_authenticated %}
<div class="row mb-2">
    <a class="btn btn-primary text-white col-11" href="{% url 'question_create' %}">Ask</a>
</div>
{% endif %}
<div class="row mr-4">
<div class="d-flex justify-content-center col-11"><h4>Trending</h4></div>
    <div class="list-group">
        {% for question in populate_q.all %}
            {% include 'question/includes/populate_question.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

question/templates/question/question_list.html
{% extends 'index.html' %}

{% block title %}
    Question List
{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
    <div class="flex-column mr-3">
       <h3>
           <a href="{% url 'question_list'%}" class="text">
                Hot questions
            </a>
       </h3>
    </div>
    <h3>|</h3>
        <div class="flex-column ml-3">
            <h3>
                <a href="{% url 'question_list_new'%}">
                    New questions
                </a>
            </h3>
        </div>
</div>


<div class="list-group">
    {% for question in object_list %}
        {% include 'question/includes/question_template.html' %}
    {% endfor %}

    {% include 'question/includes/paginator.html' %}

</div>
{% endblock %}

{% block populate %}
{% if user.is_authenticated %}
<div class="row mb-2">
    <a class="btn btn-primary text-white col-11" href="{% url 'question_create' %}">Ask</a>
</div>
{% endif %}
<div class="row mr-4">
    <div class="d-flex justify-content-center col-11"><h4>Trending</h4></div>
        <div class="list-group">
            {% for question in populate_q.all %}
                {% include 'question/includes/populate_question.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

question/templates/question/questions.html
{% extends 'index.html' %}

{% block title %}
    Question
{% endblock %}

{% block content %}

<div class="list-group">
    {% for question in object_list %}
    <div class="list-group-item d-flex flex-row mt-3">
        <div class="col-1 flex-column">
            <div class="d-flex p-2 justify-content-center">Votes</div>
            <div class="d-flex p-2 justify-content-center">{{ question.votes }}</div>
        </div>
        <span class="col-2 flex-column border border-primary">
            <div class="d-flex p-2 justify-content-center">Answer</div>
            <div class="d-flex p-2 justify-content-center">{{ question.answers.count }}</div>
        </span>
        <div class="col-9 flex-row">
            <div class="d-flex p-2 justify-content-between">
                <a href="{{ question.get_absolute_url }}">
                    <h5 class="">{{ question.title }}</h5>
                </a>
                <small>{{ question.author }}</small>
            </div>
            <div class="d-flex p-2 justify-content-between ml-5">
                <small>
                    {% for tag in question.tags.all %}
                    <span class="btn btn-success btn-sm btn-tag ml-1">
                        {{ tag.name }}
                    </span>
                    {% endfor %}
                </small>
                <small class="primary">{{ question.date_create }}</small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

question/templates/question/tag_detail.html
{% extends 'index.html' %}

{% block title %}
    {{ tag.name }}
{% endblock %}

{% block content %}
<h4>Tag: {{ tag.name }}</h4>
<div class="list-group">
    {% for question in object.all %}
        {% include 'question/includes/question_template.html' %}
    {% endfor %}

    {% include 'question/includes/paginator.html' %}
</div>
{% endblock %}

{% block populate %}
{% if user.is_authenticated %}
<div class="row mb-2">
    <a class="btn btn-primary text-white col-11" href="{% url 'question_create' %}">Ask</a>
</div>
{% endif %}
<div class="row mr-4">
    <div class="d-flex justify-content-center col-11"><h4>Trending</h4></div>
        <div class="list-group">
            {% for question in populate_q.all %}
                {% include 'question/includes/populate_question.html' %}
            {% endfor %}
        </div>
</div>
{% endblock %}